AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Zenoti Appointment Delete workflow

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0cdaf62b906f46e0e
  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: List of private subnet IDs for the Lambda function
    Default: subnet-0d4ad096b4b13c8fc,subnet-014ffa04ebbff5731,subnet-016b58cf5819cd0cd

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID
    Default: sg-02a3782f5c1927171

Resources:
  AppointmentsZenotiEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: AppointmentsZenoti

  ZenotiAppointmentDeleteRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref AppointmentsZenotiEventBus
      Name: ZenotiAppointmentDelete
      EventPattern:
        detail:
          data:
            appointments:
              id:
                - exists: false
          event_type:
            - AppointmentGroup.Updated
        source:
          - zenoti
      Targets:
        - Arn: !GetAtt DeleteAppointmentFunction.Arn
          Id: DeleteAppointmentTarget

  DeleteAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-delete-appointment
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SECRET_NAME: dev/us-west-2/dev-emr-skinlaundry-cluster/backend/emr-be
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds: !Ref PrivateSubnetIds
      Policies:
      - VPCAccessPolicy: {}
      - AWSLambdaVPCAccessExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
          - Effect: Allow
            Action:
              - rds-db:connect
            Resource: "*"

  DeleteAppointmentFunctionEventInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteAppointmentFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ZenotiAppointmentDeleteRule.Arn

Outputs:
  DeleteAppointmentFunctionArn:
    Description: ARN of the Delete Appointment Lambda function
    Value: !GetAtt DeleteAppointmentFunction.Arn
  AppointmentsZenotiEventBusArn:
    Description: ARN of the AppointmentsZenoti Event Bus
    Value: !GetAtt AppointmentsZenotiEventBus.Arn
  ZenotiAppointmentDeleteRuleArn:
    Description: ARN of the Zenoti Appointment Delete Rule
    Value: !GetAtt ZenotiAppointmentDeleteRule.Arn