version = 0.1
[default.deploy.parameters]
stack_name = "EMR-modifyAppointment"
resolve_s3 = true
s3_prefix = "EMR-modifyAppointment"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" VpcId=\"vpc-05ae8822f68ed91f7\" PrivateSubnetIds=\"subnet-026a6b674555da462,subnet-01198ce83f8760adf\" SecurityGroupId=\"sg-0dbe6cf9290ad7b3a\""
image_repositories = []
